version: '3'

services:
    pinterestapi:
        image: postgres
        container_name: database_pinterest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: pinterestapi
        restart: always
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/usr/app
        links:
            - pinterestapi
        depends_on:
            - pinterestapi

volumes:
    pgdata:
        driver: local
